sudo: false
language: cpp
compiler:
  - gcc
  - clang

install:
  # use gcc-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # create deps directory for build tools
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deps
  - cd deps
  # install newer lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - PREFIX=`pwd`/opt make -C lcov-1.11/ install
  # install coveralls-lcov
  - mkdir gems
  - gem install -i gems coveralls-lcov
  # update PATH (for lcov and coveralls-lcov)
  - DEPS=${TRAVIS_BUILD_DIR}/deps
  - PATH=${DEPS}/opt/usr/bin:${DEPS}/gems/bin:$PATH
  - GEM_PATH=${DEPS}/gems:$GEM_PATHS
  # show versions used
  - $CXX --version | head -1
  - gcov --version | head -1
  - gcov-4.8 --version | head -1
  - lcov --version | head -1

before_script:
  - cd ${TRAVIS_BUILD_DIR}/test
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}/test
  - g++-4.8 -std=c++11 -o test_notch_with_coverage --coverage -DNOTCH_USE_CBLAS -I.. test_*.cpp -L/usr/lib/openblas-base -lopenblas
  - ./test_notch_with_coverage

after_success:
  - cd ${TRAVIS_BUILD_DIR}/test
  - lcov --capture --directory . --output-file coverage.info --gcov-tool `which gcov-4.8` &&
    lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info &&
    lcov --list coverage.info &&
    coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libblas-dev
    - libopenblas-dev
